### ISSUE TITLE
Issue: bb contents <package> fails with Traceback if package hasn't been built (rather than indicating the package hasn't been built)

### ISSUE THREAD

**Issue by mbrown9764** [kergoth/bb#1]
For example, I haven't built qt4-embedded and got the following output.  Preferably we could check for .../packages-split first and give a helpful error message instead of aborting if the directory doesn't exist.

warp-3% bb contents qt4-embedded
Parsing recipes..WARNING: No recipes available for:
  /mentor/src/meibp-2013/meta-mentor/recipes/lttng-2.0/linux-omap4_3.1.0.bbappend
  /mentor/src/meibp-2013/meta-mentor/recipes/liburcu/liburcu_0.6.7.bbappend
  /mentor/src/meibp-2013/meta-oe/meta-systemd/meta-efl/recipes-efl/efl/entrance_svn.bbappend
  /mentor/src/meibp-2013/meta-oe/meta-systemd/meta-multimedia/recipes-multimedia/musicpd/mpd_0.17.1.bbappend
  /mentor/src/meibp-2013/meta-mentor/recipes/samba/samba_3.5.6.bbappend
  /mentor/src/meibp-2013/meta-oe/meta-systemd/meta-gnome/recipes-gnome/gdm/gdm_2.32.2.bbappend
  /mentor/src/meibp-2013/meta-mentor/recipes/lttng-2.0/linux-imx_3.0.15.bbappend
  /mentor/src/meibp-2013/meta-atp/recipes/fuse/linux-imx_3.0.15.bbappend
  /mentor/src/meibp-2013/meta-atp/recipes/systemd/linux-imx_3.0.15.bbappend
  /mentor/src/meibp-2013/meta-mentor/recipes/boot-format/boot-format_git.bbappend
  /mentor/src/meibp-2013/meta-mentor/recipes/lttng-2.0/linux-qoriq-sdk.bbappend
done.
Traceback (most recent call last):
  File "/home/mwbrown/sub-bb/libexec/bb-contents", line 75, in <module>
    bbcmd.run_main(main)
  File "/home/mwbrown/sub-bb/libexec/bbcmd.py", line 263, in run_main
    sys.exit(main(sys.argv[1:]) or 0)
  File "/home/mwbrown/sub-bb/libexec/bb-contents", line 71, in main
    return contents(args.recipe)
  File "/home/mwbrown/sub-bb/libexec/bb-contents", line 51, in contents
    for package in sorted(os.listdir(pkgdir)):
OSError: [Errno 2] No such file or directory: '/mentor/src/meibp-2013/build/tmp/work/mx6q-mel-linux-gnueabi/qt4-embedded-4.8.1-r55.1/packages-split'

**Comment by kergoth** [comment]
This was fixed as a side effect of the switch to use of oe-pkgdata-util:

    $ bb contents qt4-embedded
    You can also use: oe-pkgdata-util list-pkg-files -p RECIPE
    
    ERROR: Unable to find packaged recipe with name qt4-embedded
    $ echo $?
    1
