### ISSUE TITLE
'bb' utility fails on attempt to import 'commands' module

### ISSUE THREAD

**Issue by RobertBerger** [kergoth/bb#28]
I know you are aware of this: [1] Just put this issue here for completeness. (and yes I would be happy to test a newer version)

I was hit by this bug from Jethro 2.0.1 to Jethro 2.0.2.
Currently investigating if there was really an upgrade to Python 3 from 2.0.1 to 2.0.2. 
[1] https://www.mail-archive.com/yocto@yoctoproject.org/msg31101.html

**Comment by kergoth** [comment]
Jethro did not use python 3, if 2.0.2 really upgraded to it, someone made a huge mistake :) Current 'bb' master supports python 3 fine, however, if you do want to use it with a release that does use python 3.

**Comment by RobertBerger** [comment]
I am investigating all day long what's the issue. I went back to a good poky branch[1] (where bb used to work), but this does not seem to be the issue, so I went forwards to [2].

I also updated my yocto-autobuilder docker container[1] from Ubuntu 14 to 16, which might be the issue and also the yocto autobuilder itself.

To take the yocto autobuilder out of the equation I built things without the Y-AB and bb does not work.

So I suspect that the Ubuntu uprade might be the issue.

I need to stay with Jethro for a while and will upgrade to Monty as soon as possible. In the meantime I'm trying to replace bb with calls to bitbake, recipetool, devtool and friends. 

[1] https://github.com/robertberger/poky/tree/2016-02-29-jethro+
[2] https://github.com/robertberger/poky/tree/2016-10-03-jethro+
[1] https://hub.docker.com/r/reliableembeddedsystems/yocto-autobuilder/

**Comment by kergoth** [comment]
I just cloned a fresh poky on the jethro branch, cloned bb and checked out a specific commit (the commit just prior to the switch to python 3, which is d458b31), and successfully ran `bb show CC`. Could you test this?

**Comment by RobertBerger** [comment]
Latest and greatest poky master with latest and greatest bb OK: \[1]
Latest and greatest jethro with latest and greatest bb not OK: [2]
Latest and greatest jethro with bb d458b310b43d4f69afbd16362f55cf2bf5afcb24 it's OK!
Thanks!

[1] http://pastebin.com/QL6mjbzB
[2] http://pastebin.com/T1Wr8kqE

**Comment by kergoth** [comment]
Glad to hear it, I'll close this out and create a jethro branch at that commit to make it easier. Thanks.
