### ISSUE TITLE
Feature request: Ability to set a default scope (e.g. core-image-atp)

### ISSUE THREAD

**Issue by mbrown9764** [kergoth/bb#6]
For developers working on a single image for extended periods, it would be handy to be able to specify a default scope (e.g. core-image-atp) for the sub-commands, possibly via env var.  Within the bb interactive shell you could also have a command to set the scope (e.g. change from core-image-atp to core-image-base).

**Comment by kergoth** [comment]
Testing this now, with bb-list, bb-search, and bb-whatdepends obeying it:
```
$ bb set-recipe-scope foo
$ bb whatdepends ncurses
Parsing recipes..done.
Preparing task data...done
ERROR: No build target for foo

$ bb set-recipe-scope core-image-minimal
$ bb whatdepends ncurses
Parsing recipes..done.
Preparing task data...done
readline
util-linux
dpkg
bash
slang
attr
```

**Comment by kergoth** [comment]
bb-shell may need a bit more work.
